[shell]
program = "/bin/zsh"
args = ["-l"]

[env]
TERM = "xterm-256color"

[window.padding]
x = 2

[font]
size = 12.0

[font.normal]
family = "UDEV Gothic"
style = "Regular"

[font.bold]
family = "UDEV Gothic"
style = "Bold"

[font.italic]
family = "UDEV Gothic"
style = "Italic"

[font.bold_italic]
family = "UDEV Gothic"
style = "Bold Italic"

[colors.primary]
background = "#1c1c1c"
foreground = "#bcbcbc"

[colors.bright]
black = "#767676"
red = "#d7875f"
green = "#afd7af"
yellow = "#d7d787"
blue = "#87afd7"
magenta = "#d7afd7"
cyan = "#87afaf"
white = "#bcbcbc"

[colors.normal]
black = "#1c1c1c"
red = "#d75f5f"
green = "#87af87"
yellow = "#afaf87"
blue = "#5f87af"
magenta = "#af87af"
cyan = "#5f8787"
white = "#9e9e9e"
